 CREATE DATABASE ZEBRINHAAZUL;
 
 SHOW DATABASES;
 
 USE ZEBRINHAAZUL;
 
 /* TABELAS */
 
 CREATE TABLE CLIMA (
     ID_CLIMA INT PRIMARY KEY AUTO_INCREMENT,
	 CIDADE VARCHAR (30),
	 TEMPERATURA FLOAT,
	 DESCRICAO VARCHAR (200),
	 UMIDADE FLOAT,
	 PRESSAO FLOAT,
	 VELOCIDADE_VENTO FLOAT
 
 );
 
 CREATE TABLE TRANSITO (
     ID_TRANSITO INT PRIMARY KEY AUTO_INCREMENT,
	 ORIGEM VARCHAR(100),
	 DESTINO VARCHAR(100),
	 RESUMO VARCHAR (500),
	 DISTANCIA FLOAT,
	 DURACAO INT,
	 INSTRUCOES VARCHAR (500),
	 
 
 );
 
 
 /* FOREIGN KEYS */
 
 ALTER TABLE TRANSITO
 ADD COLUMN IDCLIMA INT;
 
ALTER TABLE TRANSITO ADD CONSTRAINT FK_TRANSITO_CLIMA
FOREIGN KEY (IDCLIMA) 
REFERENCES CLIMA (ID_CLIMA);

/* CRIANDO UM INDEX */

CREATE INDEX IDX_CIDADE ON CLIMA (CIDADE);

/* CONSULTA POR CIDADE NA TABELA CLIMA */

SELECT * FROM CLIMA WHERE CIDADE = "SÃO PAULO";